name: Kata Containers CI (manually triggered)
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  kata-containers-ci-on-push:
    uses: ./.github/workflows/ci.yaml
    with:
      commit-hash: ${{ github.sha }}
      pr-number: "manually-triggered"
      tag: ${{ github.sha }}-manually-triggered
      target-branch: ${{ github.ref_name }}
    secrets: inherit
